version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:2024.05.1
    steps:
      - checkout:
          path: FLARE
      - run:
          name: Install Java OpenJDK 17 for OpenRocket
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version
      - run:
          name: "Run ci.sh"
          command: source ci.sh
          path: FLARE


workflows:
  main:
    jobs:
      - test